#!/usr/bin/env zsh

# Toggle dualhead.
# Guide: http://zachstechnotes.blogspot.no/2012/04/post-title.html
# Hints for this script:  http://blog.gordin.de/post/optimus-guide
#
#
# Requirements:
#   bumblebee (https://github.com/Bumblebee-Project)
#   primus
#   screenclone (https://github.com/liskin/hybrid-screenclone)
#   intel driver patch (https://github.com/liskin/patches/blob/master/hacks/xserver-xorg-video-intel-2.20.2_virtual_crtc.patch)

# The nvidia driver seems to have trouble with reading (some) EDIDs.
# I had to manually extract it using a different computer, and specify
# that file as a customEDI in xorg.conf.nvidia.

# Ensure a single running instance of this script
# NAME=$(basename $0)
# source ~/bin/single_instance

# external monitor screen size
X=1920
Y=1200

LOCK="$HOME/.dualhead.lock"



if [[ -e $LOCK ]]; then
    killall screenclone
else
    echo -n $$ > "$LOCK"

    modeline=`cvt $X $Y | sed "1d" | sed 's/Modeline //'`
    modename=`echo $modeline | sed 's/ .*//'`

    # Add the appropriate mode, it simply fails if it is already there.
    xrandr --newmode $modeline &> /dev/null 2>&1
    xrandr --addmode VIRTUAL1 $modename

    # ... and activate it, extending the X display:
    xrandr --output LVDS1 --auto --output VIRTUAL1 --mode $modename \
           --right-of LVDS1

    trap "xrandr --output VIRTUAL1 --off; \
          killall screenclone; \
          rm $LOCK" \
         INT TERM EXIT QUIT HUP

    ## In a forking subshell, wait for the secondary X server to appear.
    ## Then, if the primary screen is inverted, invert the secondary too.
    (
        set -x;
        while [[ ! -e /tmp/.X11-unix/X8 ]]; do
            sleep 0.2
        done

        is_normal=$(xcalib -n 256 -invert -alter -verbose -display :0 \
            | head -1 | cut -d ' ' -f3)
        if (( $is_normal )); then
            xcalib -invert -alter -verbose -display :8
        fi
    ) &

    # `primusrun` starts the X server (default display :8) if it is not running.
    # We use it for launching screenclone to avoid having to set
    # KeepUnusedXServer in bumblebee.conf
    # `screenclone` clones the virtual display (xinerama display) over to the
    # new X server.
    primusrun \
        $HOME/bin/withglxcontext bash -c "xset -display :8 -dpms && \
                                          xset -display :8 s off && \
                                          screenclone -d :8 -x 1"
    exit
fi
