#!/usr/bin/env zsh

INTERNAL=false

if [[ $1 == '-i' ]]
then
    shift 1
    INTERNAL=true
fi

BIN=$(which $1)
shift 1

if $INTERNAL
then
    xinit $BIN $@ -- /usr/lib/systemd/systemd-multi-seat-x :1 -ac \
        -nolisten tcp &> /dev/null
else
    optirun --no-xorg xinit $BIN $@ -- /usr/lib/systemd/systemd-multi-seat-x \
        :1 -ac -config xorg.conf.nvidia.separate-x -nolisten tcp -sharevts \
        -novtswitch
    # sleep 1
    # DISPLAY=:1 xset -dpms
    # DISPLAY=:1 xset s off
fi
