#!/usr/bin/env zsh

## Invert X colors while root window stays black.

## Dependencies:
##     xcalib
##     xsetroot
##     single_instance script

source ~/bin/single_instance $(basename $0)

SOCKET_PATH=/tmp/.X11-unix/X
X_SOCKETS=($SOCKET_PATH*)

disp=":${X_SOCKETS[1]#$SOCKET_PATH}"
is_normal=$(xcalib -n 256 -invert -alter -verbose -display $disp \
        | head -1 | cut -d ' ' -f3)

for x in  $X_SOCKETS; do
    disp=":${x#$SOCKET_PATH}"
    xcalib -invert -alter -verbose -display $disp &
done

if (( $is_normal )); then
    feh --bg-tile ~/bin/black.png
else
    # we're inverted now, so white is actually black.
    feh --bg-tile ~/bin/white.png
fi


exit 0
